### ISSUE TITLE
Error when initializing OpenVR

### ISSUE THREAD

**Issue by spencerh-b** [uts-magic-lab/htc_vive_teleop_stuff#2]
@awesomebytes 
`Error when initializing OpenVR (try 1 / 4)
VRInitError_Init_VRClientDLLNotFound (error number 102)
`

What does this entail? Do I need steamVR running?

Where does OpenVR need to be is there a specific openVR repo I need?

**Comment by awesomebytes** [comment]
Have you used the provided launchfile?

It sets an environment variable that is needed.

**Comment by spencerh-b** [comment]
Yes I am using the vive_tf_joy... file. Is the pyopenvr that I cloned the only thing that I need?

**Comment by spencerh-b** [comment]
I did some searching into this and I was wondering if you could tell me when you run this and run .local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcmd you get a valid response. My computer seems to think that a shared library is missing

**Comment by awesomebytes** [comment]
I don't have access right now to an HTC Vive system, I can't promise I can check anytime soon.

Did you follow the instructions from here:
https://github.com/uts-magic-lab/htc_vive_teleop_stuff/blob/master/INSTALL.md
?

**Comment by spencerh-b** [comment]
I got it to work by purgeing everything and then reinstalling everything. Could have just been a broken package. Thank you so much!
