### ISSUE TITLE
Topic to access for teleoperation (Baxter)

### ISSUE THREAD

**Issue by kwunh** [uts-magic-lab/htc_vive_teleop_stuff#4]
I am bit confused about accessing the topics.. So I know that /vive_left /vive_right are for the Joy messages.  But for any teleoperation (like controlling Baxter using the Vive), would I also need to run **frame_as_posestamped.py** script to access _/left_controller_as_posestamped_ and _/right_controller_as_posestamped_ ?  

It's just I am planning to also use the headset to control head movements of Baxter once I get the arm limbs working.  So leaving the headset stationary as a reference frame is not ideal.  Would you happen to know of a workaround?  Like could it be possible to achieve teleoperation by accessing the normal /tf topic to access TFMessages (containing Pose & Quaternion)?

**Comment by awesomebytes** [comment]
Yes, frame_as_posestamped.py will publish on a PoseStamped topic the frames you want. I do recommend you to use the launch files I provide to first understand how it works (instead of running the Python files by hand, if you check the .launch files I'm doing a couple of tricks to make the life of the user easier).


For the headset part, you can just change the reference frame to be one of the sensors. You could also use the origin of coordinates of the system, which is wherever you did the setup procedure of the HTC Vive. If your HTC Vive setup is completely static, that sounds great. It wasn't my case when developing this package, so it was easier for me to use the headset as the reference frame.

**Comment by kwunh** [comment]
Ah okay, I will try the launch files first & see how it goes.
Might be a daft question but by sensors, do you mean the Lighthouses of the HTC? 
Do you have an idea of what arg I put in for the sensor?- instead of "hmd" or maybe a way to find out the name of device?  just so I know what to plug into /frame_as_posestamped.py frame_to_posestamped reference_frame [rate]

**Comment by awesomebytes** [comment]
Yeah I meant the lighthouses, sorry I'm a bit sleepy and I didn't remember the name haha

About the reference frame, you can check this image of the TF tree from the readme:

https://github.com/uts-magic-lab/htc_vive_teleop_stuff/blob/master/tf_tree.png

You'll see you could use "world" as the one from the setup or "lighthouse_0" for one lighthouse, or "lighthouse_1" for the second. I took that image when I only had one running. I don't know if there is a guarantee in the system to label 0 and 1 always the same (that comes from the internal driver) but I'd guess it stays always like that (but the controllers don't, on every turn on of the system... They may switch being left or right).

**Comment by kwunh** [comment]
Oh haha that's alright!
Thanks so much.  So since there's two lighthouses, should I set both controllers to the same one? or set the left controller to left lighthouse & vice-versa?

**Comment by awesomebytes** [comment]
I'd use the same frame of reference, I see no advantage on using different ones.

**Comment by kwunh** [comment]
Got it!
One more thing, looking at your code in **teleop_pr2.py** for your example robot- it seems to me that you used the torso as the reference frame for the ik solver for both left and right hands?  I assume this is mirroring your headset that you used as the reference frame? Perhaps the headset is set close to where a human's torso would be.

Does it mean I have to pick another reference frame depending on where I've positioned the lighthouses? (they're usually on either side of the room).  Not sure if the reference frame of the human and robot have to match up in some way.
Or would it not matter where the lighthouse is, so long as it's stationary?

**Comment by awesomebytes** [comment]
The torso is just the first link of the chain of every arm on PR2. You could arbitrarily choose anywhere as the start to translate poses from the HTC Vive reference frame to your robots reference frame.

You can also use the controllers to teleop as relative poses instead of absolute (wherever you press a button you start teleop-ing and the movement from that initial point is translated to the arm until you release the button).

It's a matter of what you want to do, there is no incorrect, just more or less convenient depending on your case.

**Comment by kwunh** [comment]
I see, I just don't really understand how it translates a human's position to a reference frame to a robot's position to a reference frame (if that makes sense).  Does this have to do with differing co-ordinate systems?  I've spent last night trying to research this && found that for the Oculus Rift, it uses a different co-ordinate system to ROS.  So I am assuming it may be the same for the HTC Vive.

I did see in the code that you do account for this using the section in **to_ros_reference_frame** but will this transformation be the same for all HTC to ROS situations? or does it depend on how the HTC was set up? I'll get a chance to actually test out code later today so hopefully it answers my confusion.

**Comment by awesomebytes** [comment]
Once you run the code (and open Rviz to check the TF frames) you'll see everything clear I think. You'll be able to answer your own questions.

On the **to_ros_reference_frame** comment, the piece of code is:
https://github.com/uts-magic-lab/htc_vive_teleop_stuff/blob/37042cda2bfad0025047380fea9f24de745b6689/scripts/vive_tf_and_joy.py#L113-L117

It just switches the axis of reference as the default way of orienting the coordinate system is different for the HTC Vive developers (maybe for the gaming community?), I found it from the OpenVR driver:
https://github.com/ValveSoftware/openvr/blob/60eb187801956ad277f1cae6680e3a410ee0873b/headers/openvr.h#L36-L40
```c++
// right-handed system
// +y is up
// +x is to the right
// -z is forward
```

ROS uses the[ right hand rule](http://www.ros.org/reps/rep-0103.html#chirality) with:
```
x forward
y left
z up
```

Coming back to your specific case:

You indeed have two coordinate systems:
1) The HTC Vive coordinate system, which you need to choose a reference frame, your `(0, 0, 0)` or origin of coordinates. Let's assume is `world`, which is set on the setup process of the HTC Vive (where you make the controller point to the computer, you leave the controller in the ground... etc). The coordinates of the controllers and headset will be given in reference to that virtual `world` reference frame.
2) The Baxter robot coordinate system. Which as reference frame you will use something like `base`, or maybe every arm has a different reference frame (as it's origin of coordinates) and you will want to use some frame of the end effector for both arms. Oh and the head.

If you want to work in absolute coordinates, you use the `world` coordinates (most probably you will want to use some offset tho) to get the pose of a controller, for example it could be `0.5, 0.1, 1.5` (0.5 meters in front, 0.1m to the left, 1.5m up) on a specific moment. Then you simply take those coordinates, and ask for a inverse kinematics to whatever IK system you have for an arm of Baxter (I'm ignoring orientation for simplicity). You may also have another offset here. And you send the arm to whatever solution you got from the IK system.

Just experiment and play, start with only one controller and one arm and you'll figure it out quickly.

**Comment by kwunh** [comment]
Thank you again for the comprehensive breakdown.
So good news! I managed to run your launch files successfully & got transformations to show up in rviz to see how it works.  

So now I'm trying to write code for Baxter to move one arm, following a similar format to PR2 example.
But I've hit another roadblock- I'm not too sure about the JointTrajectory.  Is this essentially the path it takes to achieve a pose?  I see that you have to list out all the connecting joints of either left or right arms so would I also need to do the same?

I've been trying examples from the official Baxter website using their inservice & they have a function that is used:  .pose_stamp.append() which takes in PoseStamped data as a parameter.  
I can successfully access the PoseStamped data taken from the Vive controllers through a listener which has a callback function to just print it out.  I'm assuming I can use this in the ik service function...

But is there another way to access the PoseStamped data other than through a callback? I would like to somehow save or return the PoseStamped data so I can use it for the ik function.

**Comment by awesomebytes** [comment]
You can make a simple class that stores the last pose and you use it whenever you want:

```python
#!/usr/bin/env python

import rospy
from geometry_msgs.msg import PoseStamped


class LastPose(object):
    def __init__(self):
        self._last_pose = None
        self._subs = rospy.Subscriber("/yourposetopic", PoseStamped,
                                      self._pose_cb, queue_size=1)

    def _pose_cb(self, data):
        self._last_pose = data

    def do_stuff(self):
        # Here we can do stuff with the latest data
        if self._last_pose is not None:
            # Do an IK call on the last pose

            # Send the IK to the arm
            pass

    def run(self):
        # We will do something 5Hz rate
        r = rospy.Rate(5)
        while not rospy.is_shutdown():
            self.do_stuff()
            r.sleep()


if __name__ == '__main__':
    lp = LastPose()
    lp.run()
```

You seem to be something for the IK here: http://sdk.rethinkrobotics.com/wiki/IK_Service_-_Code_Walkthrough

And something to set the position of the joints here: http://sdk.rethinkrobotics.com/wiki/Joint_Position_Keyboard_-_Code_Walkthrough

You should be able to get something kinda working with that. And from there improve it.

Good luck.

**Comment by flightlesskite** [comment]
Thanks! I managed to get something sort of going the last few days...
Managed to get some mappings through calculating offsets from my origin (the headset) and the robot's origin (the base).  
But I think I am having issues when using the hmd as the reference frame for the controllers since your code was designed to have the hmd static, whereas I'm wearing the device whilst attempting to control the robot's limbs.

So it runs fine as long as I don't move or tilt my head at all.  But then I'm fixated to a certain spot & even if I tilt my head slightly, it'll control the robot's arm.  I'm a bit confused as to why this happens since it's basically only the orientation (roll, yaw, pitch) that slightly changes when I tilt my head.  The actual position (x, y, z) shouldn't change right?

Also, I had to adjust some of the mapping for the orientation... I wonder if this is causing the issue.  Where you had: `rot.z, rot.y, rot.x = rot.y, -rot.x, -rot.z `, 
I am using `rot.z, rot.y, rot.x = -rot.x, -rot.y+90deg, -rot.z ` in order to get my robot to work.  

When I used the original mapping, his arms were all over the place... not sure if this was an issue for you?

**Comment by kwunh** [comment]
Hi sorry to bother you again, but I am really close to getting everything working as it should.
So I remember you saying that your code gets the position of the HMD headset relative to its origin point (0, 0, 0) & I am using "world" in this case.
Is there a way to recalibrate the origin point to the **current position** in which the user is standing.
The issue I am having is that I constantly have to be aligned with the origin point set by "world" aka set through play area setup (when I point the hmd to screen etc.) or else the positioning of controllers seems off.
Or would you just have to re-do the play area setup through SteamVR every time you want to recalibrate? I found that the oculus has a function:`ovr_RecenterTrackingOrigin` but I cannot find one for the HTC... would you happen to know of a workaround?
Thanks!

**Comment by kwunh** [comment]
Actually I just thought of something that may be easier.  Would it be possible to make the HMD to be the origin of co-ordinates instead of world? e.g. make the position at which the HMD is at my "world" frame essentially & get the controller positions relative to that.

**Comment by awesomebytes** [comment]
@flightlesskite A year late... (sorry, didn't see that last reply I guess). What you propose to use the HMD as the origin is exactly what I've done in some demos.
