### ISSUE TITLE
Simultaneous headset display

### ISSUE THREAD

**Issue by AndyZe** [uts-magic-lab/htc_vive_teleop_stuff#5]
Great package!

I find that this node crashes when I try to run an RViz Vive plugin. The plugin displays RViz in the Vive headset. I'm using this plugin:
https://github.com/AndreGilerson/rviz_vive_plugin

Have you had any luck with the HMD display while running teleop_stuff?

**Comment by awesomebytes** [comment]
I don't think it will work as it takes control of the device.
